title: Austin Jones
logo: /headshot.jpeg
description: austinjonesajj333@gmail.com github.com/stinojones linkedin.com/in/austinjonesajj333 720.701.2491

show_downloads: false
theme: jekyll-theme-minimal
